sonar.projectKey=prompt-jod
sonar.projectName=Prompt Jod
sonar.projectVersion=1.0

sonar.sources=app,routes,database,config
sonar.exclusions=vendor/**,node_modules/**,storage/**,public/**,tests/**,resources/**
